name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      JEMALLOC_SYS_WITH_MALLOC_CONF: narenas:1,dirty_decay_ms:0,muzzy_decay_ms:0,abort_conf:true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --release && cp target/release/api-proxy-rs api-proxy-rs

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-proxy-rs
          path: api-proxy-rs

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: action.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/yeecord/api-proxy-rs:latest
