name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  packages: write
  contents: write

env:
  JEMALLOC_SYS_WITH_MALLOC_CONF: narenas:1,dirty_decay_ms:0,muzzy_decay_ms:0,abort_conf:true
  IMAGE: ghcr.io/yeecord/api-proxy-rs

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - tag: x86
            os: ubuntu-24.04
            platform: linux/amd64
          - tag: arm64
            os: ubuntu-24.04-arm64
            platform: linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,name=cache,scope=${{ matrix.platform }},mode=max
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}-${{ matrix.tag }}
            ${{ env.IMAGE }}:latest-${{ matrix.tag }}

  create-manifest:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Multi-arch Manifest
        run: |
          docker buildx imagetools create -t ${{ env.IMAGE }}:${{ github.sha }} \
            ${{ env.IMAGE }}:${{ github.sha }}-x86 \
            ${{ env.IMAGE }}:${{ github.sha }}-arm64

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE }}:${{ github.sha }}
